/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.inexture.csvimporter.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.inexture.csvimporter.model.Goods;
import com.inexture.csvimporter.service.GoodsLocalServiceUtil;

/**
 * The extended model base implementation for the Goods service. Represents a row in the &quot;TEST_Goods&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GoodsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GoodsImpl
 * @see Goods
 * @generated
 */
@ProviderType
public abstract class GoodsBaseImpl extends GoodsModelImpl implements Goods {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a goods model instance should use the {@link Goods} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GoodsLocalServiceUtil.addGoods(this);
		}
		else {
			GoodsLocalServiceUtil.updateGoods(this);
		}
	}
}