/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.inexture.csvimporter.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Goods service. Represents a row in the &quot;TEST_Goods&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.inexture.csvimporter.model.impl.GoodsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.inexture.csvimporter.model.impl.GoodsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Goods
 * @see com.inexture.csvimporter.model.impl.GoodsImpl
 * @see com.inexture.csvimporter.model.impl.GoodsModelImpl
 * @generated
 */
@ProviderType
public interface GoodsModel extends BaseModel<Goods> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a goods model instance should use the {@link Goods} interface instead.
	 */

	/**
	 * Returns the primary key of this goods.
	 *
	 * @return the primary key of this goods
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this goods.
	 *
	 * @param primaryKey the primary key of this goods
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this goods.
	 *
	 * @return the uuid of this goods
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this goods.
	 *
	 * @param uuid the uuid of this goods
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the goods ID of this goods.
	 *
	 * @return the goods ID of this goods
	 */
	public long getGoodsId();

	/**
	 * Sets the goods ID of this goods.
	 *
	 * @param goodsId the goods ID of this goods
	 */
	public void setGoodsId(long goodsId);

	/**
	 * Returns the name of this goods.
	 *
	 * @return the name of this goods
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this goods.
	 *
	 * @param name the name of this goods
	 */
	public void setName(String name);

	/**
	 * Returns the description of this goods.
	 *
	 * @return the description of this goods
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this goods.
	 *
	 * @param description the description of this goods
	 */
	public void setDescription(String description);

	/**
	 * Returns the length of this goods.
	 *
	 * @return the length of this goods
	 */
	public double getLength();

	/**
	 * Sets the length of this goods.
	 *
	 * @param length the length of this goods
	 */
	public void setLength(double length);

	/**
	 * Returns the height of this goods.
	 *
	 * @return the height of this goods
	 */
	public double getHeight();

	/**
	 * Sets the height of this goods.
	 *
	 * @param height the height of this goods
	 */
	public void setHeight(double height);

	/**
	 * Returns the area of this goods.
	 *
	 * @return the area of this goods
	 */
	public double getArea();

	/**
	 * Sets the area of this goods.
	 *
	 * @param area the area of this goods
	 */
	public void setArea(double area);

	/**
	 * Returns the nr of this goods.
	 *
	 * @return the nr of this goods
	 */
	@AutoEscape
	public String getNr();

	/**
	 * Sets the nr of this goods.
	 *
	 * @param nr the nr of this goods
	 */
	public void setNr(String nr);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Goods goods);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Goods> toCacheModel();

	@Override
	public Goods toEscapedModel();

	@Override
	public Goods toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}